import './globals.css'
import type { Metadata } from 'next'
import React, {ReactNode} from "react";

export const metadata: Metadata = {
  title: 'UX Studio Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className="container">
        {children}
      </div>
      </body>
    </html>
  )
}
