import './globals.css'
import type { Metadata } from 'next'
import React, {ReactNode} from "react";

export const metadata: Metadata = {
  title: 'nextjs-fullstack-contactlist',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
